In [1]:
import pandas as pd

In [2]:
# 속성 기반 감성 분석 말뭉치 2021
df = pd.read_csv('clean_data.csv')
df.rename(columns = {'sentence_form':'document', 'polariry':'labels'}, inplace=True)
df.drop(['Unnamed: 0'], axis = 1, inplace=True)
df['labels'] = df['labels'].replace(['neutral', 'positive', 'negative'], [0, 1, 2])
df

                                               document  labels
0                둘쨋날은 미친듯이 밟아봤더니 기어가 헛돌면서 틱틱 소리가 나서 경악.       2
1     이거 뭐 삐꾸를 준 거 아냐 불안하고, 거금 투자한 게 왜 이래.. 싶어서 정이 확...       2
2                  간사하게도 그 이후에는 라이딩이 아주 즐거워져서 만족스럽게 탔다.       1
3     벌써 꽃가루 날리고 날벌레 날아다녀서 좀 방해되는 구간이 있긴 했지만 전반적으로 도...       1
4     샥이 없는 모델이라 일반 도로에서 타면 노면의 진동 때문에 손목이 덜덜덜 떨리고 이...       0
...                                                 ...     ...
5986                                               (슬픔)       2
5987                                          보드랍고 괜찮다!       1
5988           일본 유니클로 질이 우리나라보다 좋은 것 같으면 기분 탓인가.......       1
5989                                 마지막으로 귀여워서 집어온 모자.       1
5990                                  일본유니클로 사랑해!!!!!!!       1

[5991 rows x 2 columns]

In [3]:
# 속성 기반 감정 데이터 Ai hub train data
df_train = pd.read_csv('train.csv')
df_train.rename(columns = {'RawText':'document', 'GeneralPolarity':'labels'}, inplace=True)
df_train.drop(['Unnamed: 0'], axis = 1, inplace=True)
df_train['labels'] = df_train['labels'].replace([-1], [2]) # 부정만 2로 바꿈
df_train

                                               document  labels
0                                     가격이 착하고 디자인이 예쁩니다       1
1     시원하게  입을수 있을것 같은데 선물하신분이 너무 크다고 하시는데 반품 비용이 배보...       2
2     기존32-34사이즈 입습니다 탄력성이좋다해서 30사이즈구매했는데 밴드없는건안들어가고...       2
3     지난번에 3종 구매하고 굉장히 편하길래 요번에도 믿고 구매했어요. 포인트도 딱 이쁘...       1
4     청바지를 많이 사보긴 했는데 이렇게 스판좋은 청바지는 첨입니다. 둘째낳고 뱃살이 안...       1
...                                                 ...     ...
1829  아직 사용전입니다 ㅇㅇ 쓰다가 너무 잘찢어져 이걸로 바꿨는데 튼튼해 보여좋네요 때잘...       1
1830               진짜 이걸 왜 이제 샀을까 생각합니다 편리하고 깔끔하게 지워지네요       1
1831  평소 쓰던 제품입니다. 리필은 있는데 막대기가 없어서 막대기 포함되는거 찾아보다가 ...       1
1832  청소기능은 다른 세제기능보다 좋진 않아요. 그러나 편리성 기능은 최고입니다. 이건 ...       0
1833  엄청 짱짱할줄 알앗는데 그렇게 짱짱하진 않아요 좀 부드러운 편입니다 근데 마감이 완...       1

[1834 rows x 2 columns]

In [4]:
# 속성 기반 감성 분석 말뭉치 2021 데이터 증강
df_aug = pd.read_csv('augmentation_data.csv')
df_aug.rename(columns = {'RawText':'document', 'GeneralPolarity':'labels'}, inplace=True)
df_aug['labels'] = df_aug['labels'].replace([-1], [2]) # 부정만 2로 바꿈
df_aug

                                               document  labels
0     평소에 목주름,팔자주름에 컴플렉스가 심해서 괜찮은 제품 찾던 중이었는데 각종 방송에...       1
1     디자인이 심플하니 예뻐서 마음에 들어요^^ 더 좀 작아서 사이즈가 큰 크기도 나왔으...       0
2     오염에 포스팅이지만 제가 기록을 없음 써봅니다.최근에 구매한 노트북 5. : 물류창...       2
3     앞판이 좀 칙칙한 색이 왔지만 디자인이 맘에 듭니다..아예 별 기대 안했는데 부드럽...       1
4     우연히 써봤는데 좋아서 구매했습니다 칫솔모가 좀 약한데 전 사이사이 잘 닦이는거 같...       1
...                                                 ...     ...
3725  ㅇㅇ마스크의 크기가 더욱 넓어져 구입했습니다. 비말이나 바이러스로부터 호흡기를 안전...       1
3726  향이 부드러워 맘에 듭니다. 냄새가 오래 지속되면 좋겠습니다. 가격은 마트보다 조금...       0
3727  이상없이 배송 잘 되었어요. 할인행사중으로 저렴하게 잘 사서 기분 좋아요~ 제품의 ...       1
3728  이미지와 다르게 인식조차 처리가 너무 별로네요 -_- 거기다가 낮은 물체는 마감 못...       2
3729           뿌리염색 안 구매했습니다. 양이 생각보다 적고 염색도 잘 하려고 됩니다.       2

[3730 rows x 2 columns]

In [6]:
# 자체 제작 데이터 데이터 증강
df_card = pd.read_csv('카드광고에대한답.csv')
df_card.rename(columns = {'RawText':'document', 'GeneralPolarity':'labels'}, inplace=True)
df_card['labels'] = df_card['labels'].replace([-1], [2]) # 부정만 2로 바꿈
df_card

                                         document  labels
0                          이 카드는 혜택이 좋아요. 정말 풍부해서       1
1                          이 정말 혜택이 풍부해서 카드는 좋아요.       1
2                          이 카드는 좋아요. 풍부해서 정말 혜택이       1
3                          이 카드는 혜택이 풍부해서 정말 좋아요.       1
4                  카드 처리되어서 쉽고 빠르게 신청이 기분이 좋아졌어요.       1
..                                            ...     ...
211  사용으로 카드 인한 혜택이 명확하고, 친절한 고객 서비스 때문에 만족스러웠어요.       1
212  카드 사용으로 인한 혜택이 친절한 명확하고, 고객 서비스 때문에 만족스러웠어요.       1
213  카드 사용으로 혜택이 인한 명확하고, 친절한 고객 서비스 때문에 만족스러웠어요.       1
214          받은 광고에 언급된 혜택과 실제로 카드 혜택이 일치해서 만족해요.       1
215          카드 광고에 언급된 혜택과 혜택이 받은 실제로 일치해서 만족해요.       1

[216 rows x 2 columns]

In [7]:
# 속성 기반 감정 데이터 Ai hub validtation data
df_val = pd.read_csv('val.csv')
df_val.rename(columns = {'RawText':'document', 'GeneralPolarity':'labels'}, inplace=True)
df_val.drop(['Unnamed: 0'], axis = 1, inplace=True)
df_val['labels'] = df_val['labels'].replace([-1], [2]) # 부정만 2로 바꿈
df_val

                                              document  labels
0    엄마 사드렸는데 배도 편하게 눌러주고  미디가 길어 편하다고...다섯가지 색상 모두...       1
1    색깔도 다양하고 핏도 이쁘네요. 다만 인견이라곤해도 시원한 인견은 아니고 오늘같은 ...       0
2    사이즈가 크게 나왔으니 꼭~~확인하세요. 제가 엉덩이와 허벅지가 굵어서 사이즈를 크...       1
3    여름에 입긴 시원하거나 얇진 않고 지금 입기 딱 좋은 두께감과 지금 입기 좋은 원단...       1
4    사이즈가 조금 크게 나온거 같아요. 바지는 입으면 편하고 좋아요. 한치수 작게 주문...       0
..                                                 ...     ...
241  소비자들이 가장 많이 사용하는 상품중 고르고 고른 상품 중 하나입니다.  친구가 이...       1
242  꽃이 피는 계절이 오려고 이렇게 한 번 더 추운 것이라고 여겨야 하겠습니다.  다리...       2
243  온 가족이 사용할 수 있는 제품이라 안심하고 선택한 상품 소개해요.  가격대비 품질...       1
244  붉은 노을 속에서 멋지게 걸어 나오는 영웅의 모습과 하루 일을 끝마치고 돌아가는 믿...       1
245  이곳저곳 후기를 보고 구매해서 써본 솔직한 나의 후기를 지금부터 적으려고 합니다. ...       1

[246 rows x 2 columns]

In [8]:
# 병합
total_train_df = pd.concat([df, df_train, df_aug, df_card], axis = 0)
total_train_df

                                              document  labels
0               둘쨋날은 미친듯이 밟아봤더니 기어가 헛돌면서 틱틱 소리가 나서 경악.       2
1    이거 뭐 삐꾸를 준 거 아냐 불안하고, 거금 투자한 게 왜 이래.. 싶어서 정이 확...       2
2                 간사하게도 그 이후에는 라이딩이 아주 즐거워져서 만족스럽게 탔다.       1
3    벌써 꽃가루 날리고 날벌레 날아다녀서 좀 방해되는 구간이 있긴 했지만 전반적으로 도...       1
4    샥이 없는 모델이라 일반 도로에서 타면 노면의 진동 때문에 손목이 덜덜덜 떨리고 이...       0
..                                                 ...     ...
211       사용으로 카드 인한 혜택이 명확하고, 친절한 고객 서비스 때문에 만족스러웠어요.       1
212       카드 사용으로 인한 혜택이 친절한 명확하고, 고객 서비스 때문에 만족스러웠어요.       1
213       카드 사용으로 혜택이 인한 명확하고, 친절한 고객 서비스 때문에 만족스러웠어요.       1
214               받은 광고에 언급된 혜택과 실제로 카드 혜택이 일치해서 만족해요.       1
215               카드 광고에 언급된 혜택과 혜택이 받은 실제로 일치해서 만족해요.       1

[11771 rows x 2 columns]

In [9]:
total_train_df.to_csv('train_df.csv', index=False, encoding='utf-8-sig')

In [10]:
df_val.to_csv('val_df.csv', index=False, encoding='utf-8-sig')